displayName: Agent
schemaName: cr328_agentULlC6-
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  botSpeechSettings:
    isDomainLanguageModelEnabled: false

  gPTSettings:
    defaultSchemaName: cr328_agentULlC6-.gpt.default

  isLightweightBot: true
  aISettings:
    contentModeration: Low

template: gpt-1.1.0
language: 1033